/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ol;

/**
 *
 * @author ikko
 */
public class Adidasui extends javax.swing.JFrame {

    /**
     * Creates new form Adidasui
     */
    public Adidasui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchbar = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        cartb = new javax.swing.JButton();
        stansmith = new javax.swing.JLabel();
        sambaog = new javax.swing.JLabel();
        superstar = new javax.swing.JLabel();
        nikeb = new javax.swing.JButton();
        Adidas = new javax.swing.JButton();
        pumab = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        homeb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        superstar1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        getContentPane().add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 6, 475, 32));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/robix (3)_1.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 99, 94));

        cartb.setText("Cart");
        getContentPane().add(cartb, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 6, -1, 32));

        stansmith.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/1.png"))); // NOI18N
        getContentPane().add(stansmith, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 145, -1, -1));

        sambaog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/2.png"))); // NOI18N
        getContentPane().add(sambaog, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 205, -1, -1));

        superstar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/223.png"))); // NOI18N
        getContentPane().add(superstar, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 205, 180, 100));

        nikeb.setText("Nike");
        nikeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikebActionPerformed(evt);
            }
        });
        getContentPane().add(nikeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 56, -1, -1));

        Adidas.setText("Adidas");
        Adidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdidasActionPerformed(evt);
            }
        });
        getContentPane().add(Adidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 56, -1, -1));

        pumab.setText("Puma");
        pumab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumabActionPerformed(evt);
            }
        });
        getContentPane().add(pumab, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 56, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel3.setText("Adidas Superstar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 285, -1, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setText("₱ 7,500");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 315, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel18.setText("Adidas Samba OG");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 285, -1, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel21.setText("₱ 8,690");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 315, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel22.setText("Adidas Stan Smith ");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 285, -1, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel28.setText("₱ 6,000");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 315, -1, -1));

        homeb.setText("Home");
        homeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebActionPerformed(evt);
            }
        });
        getContentPane().add(homeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 56, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/1920x1080-lemon-yellow-solid-color-background_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, -10, 1030, 160));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/656565.png (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/1.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 150, 130));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/2.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 150, 90));

        superstar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/223.png"))); // NOI18N
        getContentPane().add(superstar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 180, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/656565.png (1)_1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
    String query = searchbar.getText().toLowerCase();
    if (query.contains("nike")) {
            nikehomepage nikePage = new nikehomepage();
            nikePage.setVisible(true);
            this.dispose();
        } else if (query.contains("adidas")) {
            Adidasui adidasPage = new Adidasui();
            adidasPage.setVisible(true);
            this.dispose();
        } else if (query.contains("puma")) {
            pumaui pumaPage = new pumaui();
            pumaPage.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_searchbarActionPerformed

    private void nikebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikebActionPerformed
    nikehomepage nikePage = new nikehomepage();
    nikePage.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_nikebActionPerformed

    private void AdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdidasActionPerformed
    Adidasui adidasPage = new Adidasui();
    adidasPage.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_AdidasActionPerformed

    private void pumabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumabActionPerformed
    pumaui pumaPage = new pumaui();
    pumaPage.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_pumabActionPerformed

    private void homebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebActionPerformed
    ALLLLPRODUCTTSS homePage = new ALLLLPRODUCTTSS();
    homePage.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_homebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adidasui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adidasui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adidasui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adidasui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adidasui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adidas;
    private javax.swing.JButton cartb;
    private javax.swing.JButton homeb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logo;
    private javax.swing.JButton nikeb;
    private javax.swing.JButton pumab;
    private javax.swing.JLabel sambaog;
    private javax.swing.JTextField searchbar;
    private javax.swing.JLabel stansmith;
    private javax.swing.JLabel superstar;
    private javax.swing.JLabel superstar1;
    // End of variables declaration//GEN-END:variables
}
