/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ol;

/**
 *
 * @author ikko
 */
public class ALLLLPRODUCTTSS extends javax.swing.JFrame {

    /**
     * Creates new form ALLLLPRODUCTTSS
     */
    public ALLLLPRODUCTTSS() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        searchbar = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        cartb = new javax.swing.JButton();
        stansmith = new javax.swing.JLabel();
        dunklow = new javax.swing.JLabel();
        retro4 = new javax.swing.JLabel();
        sambaog = new javax.swing.JLabel();
        AdidasSuperstarPic = new javax.swing.JLabel();
        speedcat = new javax.swing.JLabel();
        pumatrainer = new javax.swing.JLabel();
        pumasmash = new javax.swing.JLabel();
        airforcePic = new javax.swing.JLabel();
        nikeb = new javax.swing.JButton();
        Adidas = new javax.swing.JButton();
        pumab = new javax.swing.JButton();
        NikeAirPrice = new javax.swing.JLabel();
        AdidasSuperstarName = new javax.swing.JLabel();
        NikeDunkLowRetroName = new javax.swing.JLabel();
        NikeDunkPrice = new javax.swing.JLabel();
        AirJordan4RetroName = new javax.swing.JLabel();
        AdidasSuperstarPrice = new javax.swing.JLabel();
        airforceName = new javax.swing.JLabel();
        AdidasSambaName = new javax.swing.JLabel();
        AirJordanPrice = new javax.swing.JLabel();
        AdidasSambaPrice = new javax.swing.JLabel();
        AdidasStanName = new javax.swing.JLabel();
        PumaSpeedName = new javax.swing.JLabel();
        PumaSuperLogoName = new javax.swing.JLabel();
        PumaSmashName = new javax.swing.JLabel();
        AdidasStanPrice = new javax.swing.JLabel();
        PumaSpeedPrice = new javax.swing.JLabel();
        PumaSuperLogoPrice = new javax.swing.JLabel();
        PumaSmashPrice = new javax.swing.JLabel();
        homeb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AirJordan4RetroPic = new javax.swing.JLabel();
        PumaSmashPic = new javax.swing.JLabel();
        NikeDunkLowRetroPic = new javax.swing.JLabel();
        AdidasSamabaPic = new javax.swing.JLabel();
        AdidasStanPic = new javax.swing.JLabel();
        PumaSpeedPic = new javax.swing.JLabel();
        PumaSuperLogoPic = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        jPanel2.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 480, 32));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/robix (3)_1.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 99, 94));

        cartb.setText("Cart");
        jPanel2.add(cartb, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, -1, 32));

        stansmith.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/1.png"))); // NOI18N
        jPanel2.add(stansmith, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        dunklow.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        dunklow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/image_2025-05-05_130037383-removebg-preview.png"))); // NOI18N
        jPanel2.add(dunklow, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, 150));

        retro4.setBackground(new java.awt.Color(255, 255, 102));
        retro4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        retro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/image_2025-05-05_130250812-removebg-preview (2).png"))); // NOI18N
        jPanel2.add(retro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, 190));

        sambaog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/2.png"))); // NOI18N
        jPanel2.add(sambaog, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, -1));

        AdidasSuperstarPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/223.png"))); // NOI18N
        jPanel2.add(AdidasSuperstarPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 180, 100));

        speedcat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/puma1.png"))); // NOI18N
        jPanel2.add(speedcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 790, -1, 80));

        pumatrainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/puma2.png"))); // NOI18N
        jPanel2.add(pumatrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 800, -1, 60));

        pumasmash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/puma3.png"))); // NOI18N
        jPanel2.add(pumasmash, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 790, -1, 70));

        airforcePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/nike air.png"))); // NOI18N
        jPanel2.add(airforcePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 160, 120));

        nikeb.setText("Nike");
        nikeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikebActionPerformed(evt);
            }
        });
        jPanel2.add(nikeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        Adidas.setText("Adidas");
        Adidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdidasActionPerformed(evt);
            }
        });
        jPanel2.add(Adidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        pumab.setText("Puma");
        pumab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumabActionPerformed(evt);
            }
        });
        jPanel2.add(pumab, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));

        NikeAirPrice.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        NikeAirPrice.setText("₱ 6,500");
        jPanel2.add(NikeAirPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        AdidasSuperstarName.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        AdidasSuperstarName.setText("Adidas Superstar");
        jPanel2.add(AdidasSuperstarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, -1, 30));

        NikeDunkLowRetroName.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        NikeDunkLowRetroName.setText("Nike Dunk Low Retro");
        jPanel2.add(NikeDunkLowRetroName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, 50));

        NikeDunkPrice.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        NikeDunkPrice.setText("₱ 5,890");
        jPanel2.add(NikeDunkPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        AirJordan4RetroName.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        AirJordan4RetroName.setText("Air Jordan 4 Retro 'Aluminum' ");
        jPanel2.add(AirJordan4RetroName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, -1, 60));

        AdidasSuperstarPrice.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        AdidasSuperstarPrice.setText("₱ 7,500");
        jPanel2.add(AdidasSuperstarPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, -1, -1));

        airforceName.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        airforceName.setText("Nike Air Force 1 Low ");
        jPanel2.add(airforceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, 30));

        AdidasSambaName.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        AdidasSambaName.setText("Adidas Samba OG");
        jPanel2.add(AdidasSambaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, -1, 30));

        AirJordanPrice.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        AirJordanPrice.setText("₱ 12.000");
        jPanel2.add(AirJordanPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, -1, -1));

        AdidasSambaPrice.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        AdidasSambaPrice.setText("₱ 8,690");
        jPanel2.add(AdidasSambaPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, -1, -1));

        AdidasStanName.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        AdidasStanName.setText("Adidas Stan Smith ");
        jPanel2.add(AdidasStanName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, -1, 30));

        PumaSpeedName.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        PumaSpeedName.setText("Puma Speed Cat OG");
        jPanel2.add(PumaSpeedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 870, -1, 30));

        PumaSuperLogoName.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        PumaSuperLogoName.setText("Puma 2.0 Super Logo Trainers");
        jPanel2.add(PumaSuperLogoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 870, -1, 30));

        PumaSmashName.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        PumaSmashName.setText("Puma Smash V2 Sneakers");
        jPanel2.add(PumaSmashName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 870, -1, 30));

        AdidasStanPrice.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        AdidasStanPrice.setText("₱ 6,000");
        jPanel2.add(AdidasStanPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 640, -1, -1));

        PumaSpeedPrice.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        PumaSpeedPrice.setText("₱ 7,000");
        jPanel2.add(PumaSpeedPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 910, -1, -1));

        PumaSuperLogoPrice.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        PumaSuperLogoPrice.setText("₱ 1,500");
        jPanel2.add(PumaSuperLogoPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 910, -1, -1));

        PumaSmashPrice.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        PumaSmashPrice.setText("₱ 1,600");
        jPanel2.add(PumaSmashPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 910, -1, -1));

        homeb.setText("Home");
        homeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebActionPerformed(evt);
            }
        });
        jPanel2.add(homeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/1920x1080-lemon-yellow-solid-color-background_1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 180));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/656565.png (1).png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 1080, -1));

        AirJordan4RetroPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/3.png"))); // NOI18N
        jPanel2.add(AirJordan4RetroPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 190, 110));

        PumaSmashPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/puma3.png"))); // NOI18N
        jPanel2.add(PumaSmashPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 780, 150, 90));

        NikeDunkLowRetroPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/nike du.png"))); // NOI18N
        jPanel2.add(NikeDunkLowRetroPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 150, 90));

        AdidasSamabaPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/2.png"))); // NOI18N
        jPanel2.add(AdidasSamabaPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 150, 90));

        AdidasStanPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/1.png"))); // NOI18N
        jPanel2.add(AdidasStanPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 150, 130));

        PumaSpeedPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/puma1.png"))); // NOI18N
        jPanel2.add(PumaSpeedPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 780, 150, 90));

        PumaSuperLogoPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/puma2.png"))); // NOI18N
        jPanel2.add(PumaSuperLogoPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 780, 150, 90));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/656565.png (1)_1.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 920, 800));

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1315, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        String query = searchbar.getText().toLowerCase();
        if (query.contains("nike")) {
            nikehomepage nikePage = new nikehomepage();
            nikePage.setVisible(true);
            this.dispose();
        } else if (query.contains("adidas")) {
            Adidasui adidasPage = new Adidasui();
            adidasPage.setVisible(true);
            this.dispose();
        } else if (query.contains("puma")) {
            pumaui pumaPage = new pumaui();
            pumaPage.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_searchbarActionPerformed
    }
    private void nikebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikebActionPerformed
        nikehomepage nikePage = new nikehomepage();
        nikePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nikebActionPerformed

    private void AdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdidasActionPerformed
        Adidasui adidasPage = new Adidasui();
        adidasPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdidasActionPerformed

    private void pumabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumabActionPerformed
        pumaui pumaPage = new pumaui();
        pumaPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pumabActionPerformed

    private void homebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebActionPerformed
        ALLLLPRODUCTTSS homePage = new ALLLLPRODUCTTSS();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ALLLLPRODUCTTSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ALLLLPRODUCTTSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ALLLLPRODUCTTSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ALLLLPRODUCTTSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ALLLLPRODUCTTSS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adidas;
    private javax.swing.JLabel AdidasSamabaPic;
    private javax.swing.JLabel AdidasSambaName;
    private javax.swing.JLabel AdidasSambaPrice;
    private javax.swing.JLabel AdidasStanName;
    private javax.swing.JLabel AdidasStanPic;
    private javax.swing.JLabel AdidasStanPrice;
    private javax.swing.JLabel AdidasSuperstarName;
    private javax.swing.JLabel AdidasSuperstarPic;
    private javax.swing.JLabel AdidasSuperstarPrice;
    private javax.swing.JLabel AirJordan4RetroName;
    private javax.swing.JLabel AirJordan4RetroPic;
    private javax.swing.JLabel AirJordanPrice;
    private javax.swing.JLabel NikeAirPrice;
    private javax.swing.JLabel NikeDunkLowRetroName;
    private javax.swing.JLabel NikeDunkLowRetroPic;
    private javax.swing.JLabel NikeDunkPrice;
    private javax.swing.JLabel PumaSmashName;
    private javax.swing.JLabel PumaSmashPic;
    private javax.swing.JLabel PumaSmashPrice;
    private javax.swing.JLabel PumaSpeedName;
    private javax.swing.JLabel PumaSpeedPic;
    private javax.swing.JLabel PumaSpeedPrice;
    private javax.swing.JLabel PumaSuperLogoName;
    private javax.swing.JLabel PumaSuperLogoPic;
    private javax.swing.JLabel PumaSuperLogoPrice;
    private javax.swing.JLabel airforceName;
    private javax.swing.JLabel airforcePic;
    private javax.swing.JButton cartb;
    private javax.swing.JLabel dunklow;
    private javax.swing.JButton homeb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logo;
    private javax.swing.JButton nikeb;
    private javax.swing.JButton pumab;
    private javax.swing.JLabel pumasmash;
    private javax.swing.JLabel pumatrainer;
    private javax.swing.JLabel retro4;
    private javax.swing.JLabel sambaog;
    private javax.swing.JTextField searchbar;
    private javax.swing.JLabel speedcat;
    private javax.swing.JLabel stansmith;
    // End of variables declaration//GEN-END:variables
}
