/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package comprog;

/**
 *
 * @author CLR2-38
 */
public class ALLPRODUCTS extends javax.swing.JFrame {

private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scrollPane;
    
    public ALLPRODUCTS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchbar = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        cartb = new javax.swing.JButton();
        stansmith = new javax.swing.JLabel();
        dunklow = new javax.swing.JLabel();
        retro4 = new javax.swing.JLabel();
        sambaog = new javax.swing.JLabel();
        superstar = new javax.swing.JLabel();
        new9060 = new javax.swing.JLabel();
        new574 = new javax.swing.JLabel();
        new550 = new javax.swing.JLabel();
        speedcat = new javax.swing.JLabel();
        pumatrainer = new javax.swing.JLabel();
        pumasmash = new javax.swing.JLabel();
        airforce = new javax.swing.JLabel();
        nikeb = new javax.swing.JButton();
        Adidas = new javax.swing.JButton();
        pumab = new javax.swing.JButton();
        newbalanceb = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        homeb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchbar.setText("Search");
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        getContentPane().add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 475, 32));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/robix (3).png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 99, 94));

        cartb.setText("Cart");
        getContentPane().add(cartb, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, 32));

        stansmith.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/1.png"))); // NOI18N
        getContentPane().add(stansmith, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        dunklow.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        dunklow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/image_2025-05-05_130037383-removebg-preview.png"))); // NOI18N
        getContentPane().add(dunklow, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, 150));

        retro4.setBackground(new java.awt.Color(255, 255, 102));
        retro4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        retro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/image_2025-05-05_130250812-removebg-preview (2).png"))); // NOI18N
        getContentPane().add(retro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, 190));

        sambaog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/2.png"))); // NOI18N
        getContentPane().add(sambaog, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        superstar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/223.png"))); // NOI18N
        getContentPane().add(superstar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 180, 100));

        new9060.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/new.png"))); // NOI18N
        getContentPane().add(new9060, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1030, -1, -1));

        new574.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/new1.png"))); // NOI18N
        getContentPane().add(new574, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 1060, -1, 60));

        new550.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/new2.png"))); // NOI18N
        getContentPane().add(new550, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1030, -1, -1));

        speedcat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/puma1.png"))); // NOI18N
        getContentPane().add(speedcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 780, -1, 80));

        pumatrainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/puma2.png"))); // NOI18N
        getContentPane().add(pumatrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 790, -1, 60));

        pumasmash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/puma3.png"))); // NOI18N
        getContentPane().add(pumasmash, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 790, -1, 70));

        airforce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/image_2025-05-05_125531236-removebg-preview.png"))); // NOI18N
        getContentPane().add(airforce, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 160, 120));

        nikeb.setText("Nike");
        nikeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikebActionPerformed(evt);
            }
        });
        getContentPane().add(nikeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        Adidas.setText("Adidas");
        Adidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdidasActionPerformed(evt);
            }
        });
        getContentPane().add(Adidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        pumab.setText("Puma");
        pumab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumabActionPerformed(evt);
            }
        });
        getContentPane().add(pumab, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        newbalanceb.setText("New Balance");
        newbalanceb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbalancebActionPerformed(evt);
            }
        });
        getContentPane().add(newbalanceb, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("₱ 6,500");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel3.setText("Adidas Superstar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel8.setText("Nike Dunk Low Retro");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 292, -1, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel11.setText("₱ 5,890");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel14.setText("Air Jordan 4 Retro 'Aluminum' ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, 60));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setText("₱ 7,500");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 620, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel16.setText("Nike Air Force 1 Low ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 302, -1, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel17.setText("New balance 9060");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1110, -1, 50));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel18.setText("Adidas Samba OG");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel19.setText("₱ 12.000");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel20.setText("₱ 8,500");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 1150, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel21.setText("₱ 8,690");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel22.setText("Adidas Stan Smith ");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, -1, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel23.setText("Puma Speed Cat OG");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 850, -1, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel24.setText("Puma 2.0 Super Logo Trainers");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 850, -1, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel25.setText("Puma Smash V2 Sneakers");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 850, -1, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel26.setText("New Balance 574");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1120, -1, 30));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel27.setText("Trainers New Balance 550");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1120, -1, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel28.setText("₱ 6,000");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel29.setText("₱ 7,000");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 880, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel30.setText("₱ 1,500");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 880, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel31.setText("₱ 1,600");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 880, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel32.setText("₱ 4,000");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 1150, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel33.setText("₱ 5,995");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1150, -1, -1));

        homeb.setText("Home");
        getContentPane().add(homeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void nikebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikebActionPerformed

    private void AdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdidasActionPerformed

    private void newbalancebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbalancebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newbalancebActionPerformed

    private void pumabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pumabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ALLPRODUCTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ALLPRODUCTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ALLPRODUCTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ALLPRODUCTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ALLPRODUCTS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adidas;
    private javax.swing.JLabel airforce;
    private javax.swing.JButton cartb;
    private javax.swing.JLabel dunklow;
    private javax.swing.JButton homeb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel new550;
    private javax.swing.JLabel new574;
    private javax.swing.JLabel new9060;
    private javax.swing.JButton newbalanceb;
    private javax.swing.JButton nikeb;
    private javax.swing.JButton pumab;
    private javax.swing.JLabel pumasmash;
    private javax.swing.JLabel pumatrainer;
    private javax.swing.JLabel retro4;
    private javax.swing.JLabel sambaog;
    private javax.swing.JTextField searchbar;
    private javax.swing.JLabel speedcat;
    private javax.swing.JLabel stansmith;
    private javax.swing.JLabel superstar;
    // End of variables declaration//GEN-END:variables
}
