/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ol;
import javax.swing.JRadioButton;
import javax.swing.BoxLayout;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;


/**
 *
 * @author eiron
 */
public class CartFrame extends javax.swing.JPanel {


private final ArrayList<JRadioButton> cartItems = new ArrayList<>();
private final HashMap<JRadioButton, String> itemProductNames = new HashMap<>();
private final HashMap<JRadioButton, Integer> itemQuantities = new HashMap<>();
private final ButtonGroup buttonGroup = new ButtonGroup();

    /**
     * Creates new form nikuy
     */
    
    public CartFrame() {
        initComponents();
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS)); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RemoveBtn = new javax.swing.JButton();
        CheckOutBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/robix (3).png"))); // NOI18N
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 99, 94));

        jButton3.setText("Home");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/1920x1080-lemon-yellow-solid-color-background.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 520, 140));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 370, 440));

        RemoveBtn.setText("Remove");
        RemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBtnActionPerformed(evt);
            }
        });
        add(RemoveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, -1, -1));

        CheckOutBtn.setText("Check Out");
        CheckOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutBtnActionPerformed(evt);
            }
        });
        add(CheckOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/656565.png (1).png"))); // NOI18N
        jLabel9.setText("jLabel9");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, -100, 780, 1170));
    }// </editor-fold>//GEN-END:initComponents
public void addItemToCart(String productName, String price, int quantity, String size) {
    String itemDetails = productName + " | " + price + " | Qty: " + quantity + " | Size: " + size;
    JRadioButton itemButton = new JRadioButton(itemDetails);
    cartItems.add(itemButton);
    itemProductNames.put(itemButton, productName);
    itemQuantities.put(itemButton, quantity);
    buttonGroup.add(itemButton);  // Needed for single-selection and remove

    jPanel1.add(itemButton);
    jPanel1.revalidate();
    jPanel1.repaint();
}


    private void CheckOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutBtnActionPerformed
        // TODO add your handling code here:
    
        // TODO add your handling code here:
            for (JRadioButton item : cartItems) {
        String productName = itemProductNames.get(item);
        int quantity = itemQuantities.get(item);

        // Reduce stock using Manage_Products
        Manage_Products.reduceStock(productName, quantity);
    }

    // Show confirmation
    javax.swing.JOptionPane.showMessageDialog(this, "Checkout complete.");

    // Clear cart visually and internally
    jPanel1.removeAll();
    cartItems.clear();
    itemProductNames.clear();
    itemQuantities.clear();
    buttonGroup.clearSelection();
    jPanel1.revalidate();
    jPanel1.repaint();
    //GEN-LAST:event_CheckOutBtnActionPerformed
    }//GEN-LAST:event_CheckOutBtnActionPerformed

    private void RemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBtnActionPerformed
        // TODO add your handling code here:
            JRadioButton toRemove = null;
    for (JRadioButton item : cartItems) {
        if (item.isSelected()) {
            toRemove = item;
            break;
        }
    }

    if (toRemove != null) {
        jPanel1.remove(toRemove);
        cartItems.remove(toRemove);
        itemProductNames.remove(toRemove);
        itemQuantities.remove(toRemove);
        buttonGroup.remove(toRemove);
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    }//GEN-LAST:event_RemoveBtnActionPerformed
    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            javax.swing.JFrame frame = new javax.swing.JFrame("Nike Product Page");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.getContentPane().add(new CartFrame());
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            
           
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckOutBtn;
    private javax.swing.JButton RemoveBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
