/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ol;

/**
 *
 * @author ikko
 */
public class nikehomepage extends javax.swing.JFrame {

    /**
     * Creates new form nikehomepage
     */
    public nikehomepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchbar = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        cartb = new javax.swing.JButton();
        dunklow = new javax.swing.JLabel();
        retro4 = new javax.swing.JLabel();
        airforce = new javax.swing.JLabel();
        nikeb = new javax.swing.JButton();
        Adidas = new javax.swing.JButton();
        pumab = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        homeb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        airforce1 = new javax.swing.JLabel();
        airforce2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        jPanel1.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 475, 32));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/robix (3)_1.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 99, 94));

        cartb.setText("Cart");
        jPanel1.add(cartb, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, 32));

        dunklow.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        dunklow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/image_2025-05-05_130037383-removebg-preview.png"))); // NOI18N
        jPanel1.add(dunklow, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, 150));

        retro4.setBackground(new java.awt.Color(255, 255, 102));
        retro4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        retro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/image_2025-05-05_130250812-removebg-preview (2).png"))); // NOI18N
        jPanel1.add(retro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, 190));

        airforce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/nike du.png"))); // NOI18N
        jPanel1.add(airforce, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 180, 120));

        nikeb.setText("Nike");
        nikeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikebActionPerformed(evt);
            }
        });
        jPanel1.add(nikeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        Adidas.setText("Adidas");
        Adidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdidasActionPerformed(evt);
            }
        });
        jPanel1.add(Adidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        pumab.setText("Puma");
        pumab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumabActionPerformed(evt);
            }
        });
        jPanel1.add(pumab, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("₱ 6,500");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel8.setText("Nike Dunk Low Retro");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 292, -1, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel11.setText("₱ 5,890");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel14.setText("Air Jordan 4 Retro 'Aluminum' ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, 60));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel16.setText("Nike Air Force 1 Low ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 302, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel19.setText("₱ 12.000");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));

        homeb.setText("Home");
        homeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebActionPerformed(evt);
            }
        });
        jPanel1.add(homeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/1920x1080-lemon-yellow-solid-color-background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -10, -1, 170));

        airforce1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/image_2025-05-05_130250812-removebg-preview (2).png"))); // NOI18N
        jPanel1.add(airforce1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 160, 120));

        airforce2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/nike air.png"))); // NOI18N
        jPanel1.add(airforce2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 160, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/656565.png (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/1920x1080-lemon-yellow-solid-color-background_1.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1490, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/656565.png (1)_1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        String query = searchbar.getText().toLowerCase();
        if (query.contains("nike")) {
            nikehomepage nikePage = new nikehomepage();
            nikePage.setVisible(true);
            this.dispose();
        } else if (query.contains("adidas")) {
            Adidasui adidasPage = new Adidasui();
            adidasPage.setVisible(true);
            this.dispose();
        } else if (query.contains("puma")) {
            pumaui pumaPage = new pumaui();
            pumaPage.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_searchbarActionPerformed

    private void nikebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikebActionPerformed
        nikehomepage nikePage = new nikehomepage();
        nikePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nikebActionPerformed

    private void AdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdidasActionPerformed
        Adidasui adidasPage = new Adidasui();
        adidasPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdidasActionPerformed

    private void pumabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumabActionPerformed
        pumaui pumaPage = new pumaui();
        pumaPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pumabActionPerformed

    private void homebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebActionPerformed
        ALLLLPRODUCTTSS homePage = new ALLLLPRODUCTTSS();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nikehomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nikehomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nikehomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nikehomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nikehomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adidas;
    private javax.swing.JLabel airforce;
    private javax.swing.JLabel airforce1;
    private javax.swing.JLabel airforce2;
    private javax.swing.JButton cartb;
    private javax.swing.JLabel dunklow;
    private javax.swing.JButton homeb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton nikeb;
    private javax.swing.JButton pumab;
    private javax.swing.JLabel retro4;
    private javax.swing.JTextField searchbar;
    // End of variables declaration//GEN-END:variables
}
