/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ol;


import javax.swing.*;
import javax.swing.JButton;
/**
 *
 * @author eiron
 */

public class nikuy extends JPanel {

private CartFrame cartFrame;    
private BabyAlien db;

    
public nikuy() {
    initComponents();
    updateProductDisplay();
    cartFrame = new CartFrame();

}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        PName = new javax.swing.JLabel();
        PriceNumber = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Size = new javax.swing.JComboBox<>();
        Quantity = new javax.swing.JSpinner();
        jlabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NoStock = new javax.swing.JLabel();
        addToCartBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/robix (3).png"))); // NOI18N
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 99, 94));

        jButton2.setText("Cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, 30));

        PName.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        PName.setText("Nike Air Force 1 Low");
        add(PName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        PriceNumber.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        PriceNumber.setText("₱ 6,500");
        add(PriceNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 60, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setText("Size (US Size)");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/AIR+FORCE+1+'07 (1).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 190, 230));

        Size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an option", "7", "8", "9" }));
        Size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeActionPerformed(evt);
            }
        });
        add(Size, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        Quantity.setValue(1);
        add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 70, -1));

        jlabel.setText("Stock's left:");
        add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("Quantity");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, -1));

        NoStock.setText("0");
        add(NoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        addToCartBtn.setBackground(new java.awt.Color(255, 215, 0));
        addToCartBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addToCartBtn.setText("Add to Cart");
        addToCartBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addToCartBtn.setFocusPainted(false);
        addToCartBtn.setOpaque(true);
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });
        add(addToCartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, 30));

        jButton1.setText("Home");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/1920x1080-lemon-yellow-solid-color-background (1).jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 520, 140));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/656565.png (1).png"))); // NOI18N
        jLabel9.setText("jLabel9");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, -100, 780, 1170));
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void SizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SizeActionPerformed

    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        // TODO add your handling code here:        String selectedSize = (String) jComboBox1.getSelectedItem();
    String selectedSize = (String) Size.getSelectedItem();
    int quantity = (Integer) Quantity.getValue();

    String stockText = NoStock.getText().replaceAll("[^0-9]", "");
    int availableStock = Integer.parseInt(stockText);

    if ("Choose an option".equals(selectedSize)) {
        JOptionPane.showMessageDialog(this, "Please select a size");
        return;
    }

    if (quantity > availableStock) {
        JOptionPane.showMessageDialog(this, "Not enough stock available");
        return;
    }

    String price = PriceNumber.getText().replace("₱", "").trim();
    String productName = PName.getText();

    if (cartFrame != null) {
        cartFrame.addItemToCart(productName, price, quantity, selectedSize);

        // 🔁 Replace current panel with cartFrame
        SwingUtilities.invokeLater(() -> {
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            topFrame.getContentPane().removeAll();
            topFrame.getContentPane().add(cartFrame);
            topFrame.revalidate();
            topFrame.repaint();
        });
    }
    
    }//GEN-LAST:event_addToCartBtnActionPerformed
    public void updateProductDisplay() {
    BabyAlien db = new BabyAlien();
    String[] productDetails = db.getFirstProductDetails();

    if (productDetails != null && productDetails.length == 3) {
        PName.setText(productDetails[0]);                   // SHOENAME
        PriceNumber.setText("₱" + productDetails[1]);       // PRICE
        NoStock.setText("Stock: " + productDetails[2]);     // STOCK
    } else {
        PName.setText("No product found");
        PriceNumber.setText("₱0.00");
        NoStock.setText("Stock: 0");
    }
    }   
    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            javax.swing.JFrame frame = new javax.swing.JFrame("Nike Product Page");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.getContentPane().add(new nikuy());
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
    });
    }
    public void setProductDetails(String name, String price, String stock) {
    PName.setText(name);
    PriceNumber.setText(price);
    NoStock.setText(stock);
}
    


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NoStock;
    private javax.swing.JLabel PName;
    private javax.swing.JLabel PriceNumber;
    private javax.swing.JSpinner Quantity;
    private javax.swing.JComboBox<String> Size;
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
