/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ol;

import javax.swing.*;
import javax.swing.JButton;
/**
 *
 * @author eiron
 */
public class nikuy3 extends javax.swing.JPanel {

private CartFrame cartFrame;    
private BabyAlien db;

    
public nikuy3() {
    initComponents();
    updateProductDisplay2();
    cartFrame = new CartFrame();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        je = new javax.swing.JLabel();
        pr = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sz = new javax.swing.JComboBox<>();
        er = new javax.swing.JSpinner();
        ok = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/robix (3).png"))); // NOI18N
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 99, 94));

        jButton2.setText("Cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, 30));

        je.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        je.setText("Air Jordan 4 Retro 'Aluminum' ");
        add(je, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        pr.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        pr.setText("₱ 12.000");
        add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 60, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setText("Size");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/women-s-air-jordan-4-aluminum-hv0823-100-release-date (1).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 180, 230));

        sz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an option", "7", "8", "9" }));
        sz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szActionPerformed(evt);
            }
        });
        add(sz, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        er.setValue(1);
        add(er, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 70, -1));

        ok.setText("Stock's left:");
        add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("Quantity");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 215, 0));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setText("Add to Cart");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, 30));

        jButton3.setText("Home");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/1920x1080-lemon-yellow-solid-color-background.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 520, 140));

        jLabel2.setText("0");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/656565.png (1).png"))); // NOI18N
        jLabel9.setText("jLabel9");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, -100, 780, 1170));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void szActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_szActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String selectedSize = (String) sz.getSelectedItem();
    int quantity = (Integer) er.getValue();

    String stockText = ok.getText().replaceAll("[^0-9]", "");
    int availableStock = Integer.parseInt(stockText);

    if ("Choose an option".equals(selectedSize)) {
        JOptionPane.showMessageDialog(this, "Please select a size");
        return;
    }

    if (quantity > availableStock) {
        JOptionPane.showMessageDialog(this, "Not enough stock available");
        return;
    }

    String price = pr.getText().replace("₱", "").trim();
    String productName = pro.getText();

    if (cartFrame != null) {
        cartFrame.addItemToCart(productName, price, quantity, selectedSize);

        // 🔁 Replace current panel with cartFrame
        SwingUtilities.invokeLater(() -> {
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            topFrame.getContentPane().removeAll();
            topFrame.getContentPane().add(cartFrame);
            topFrame.revalidate();
            topFrame.repaint();
        });
    }
    
    }                                            
    public void updateProductDisplay2() {
    BabyAlien db = new BabyAlien();
    String[] productDetails = db.getFirstProductDetails();  

    if (productDetails != null && productDetails.length == 3) {
        je.setText(productDetails[0]);                   // SHOENAME
        pr.setText("₱" + productDetails[1]);       // PRICE
        ok.setText("Stock: " + productDetails[2]);     // STOCK
    } else {
        je.setText("No product found");
        pr.setText("₱0.00");
        ok.setText("Stock: 0");
    }
    }   
    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            javax.swing.JFrame frame = new javax.swing.JFrame("Nike Product Page");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.getContentPane().add(new nikuy3());
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
    });
    }
    public void setProductDetails(String name, String price, String stock) {
    je.setText(name);
    pr.setText(price);
    ok.setText(stock);
    }                                        
    }//GEN-LAST:event_jButton1ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner er;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel je;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel ok;
    private javax.swing.JLabel pr;
    private javax.swing.JComboBox<String> sz;
    // End of variables declaration//GEN-END:variables

