/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ol;

/**
 *
 * @author ikko
 */
public class pumaui extends javax.swing.JFrame {

    /**
     * Creates new form pumaui
     */
    public pumaui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchbar = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        cartb = new javax.swing.JButton();
        speedcat = new javax.swing.JLabel();
        pumatrainer = new javax.swing.JLabel();
        pumasmash = new javax.swing.JLabel();
        nikeb = new javax.swing.JButton();
        Adidas = new javax.swing.JButton();
        pumab = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        homeb = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        getContentPane().add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 475, 32));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/robix (3)_1.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 99, 94));

        cartb.setText("Cart");
        getContentPane().add(cartb, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, 32));

        speedcat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/puma1.png"))); // NOI18N
        getContentPane().add(speedcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 220, -1, 80));

        pumatrainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/puma2.png"))); // NOI18N
        getContentPane().add(pumatrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 230, -1, 60));

        pumasmash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/puma3.png"))); // NOI18N
        getContentPane().add(pumasmash, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 230, -1, 70));

        nikeb.setText("Nike");
        nikeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikebActionPerformed(evt);
            }
        });
        getContentPane().add(nikeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 80, -1, -1));

        Adidas.setText("Adidas");
        Adidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdidasActionPerformed(evt);
            }
        });
        getContentPane().add(Adidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 80, -1, -1));

        pumab.setText("Puma");
        pumab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumabActionPerformed(evt);
            }
        });
        getContentPane().add(pumab, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 80, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel23.setText("Puma Speed Cat OG");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 290, -1, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel24.setText("Puma 2.0 Super Logo Trainers");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 290, -1, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel25.setText("Puma Smash V2 Sneakers");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 290, -1, 30));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel29.setText("₱ 7,000");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 320, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel30.setText("₱ 1,500");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 320, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel31.setText("₱ 1,600");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 320, -1, -1));

        homeb.setText("Home");
        homeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebActionPerformed(evt);
            }
        });
        getContentPane().add(homeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 80, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprog/656565.png (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/1920x1080-lemon-yellow-solid-color-background_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -10, 1050, 170));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/puma2.png"))); // NOI18N
        jLabel10.setAutoscrolls(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 150, 130));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/puma3.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 150, 130));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/puma1.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 150, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ol/656565.png (1)_1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
    String query = searchbar.getText().toLowerCase();
    if (query.contains("nike")) {
            nikehomepage nikePage = new nikehomepage();
            nikePage.setVisible(true);
            this.dispose();
        } else if (query.contains("adidas")) {
            Adidasui adidasPage = new Adidasui();
            adidasPage.setVisible(true);
            this.dispose();
        } else if (query.contains("puma")) {
            pumaui pumaPage = new pumaui();
            pumaPage.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_searchbarActionPerformed

    private void nikebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikebActionPerformed
    nikehomepage nikePage = new nikehomepage();
    nikePage.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_nikebActionPerformed

    private void AdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdidasActionPerformed
    Adidasui adidasPage = new Adidasui();
    adidasPage.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_AdidasActionPerformed

    private void pumabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumabActionPerformed
    pumaui pumaPage = new pumaui();
    pumaPage.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_pumabActionPerformed

    private void homebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebActionPerformed
    ALLLLPRODUCTTSS homePage = new ALLLLPRODUCTTSS();
    homePage.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_homebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pumaui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pumaui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pumaui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pumaui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pumaui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adidas;
    private javax.swing.JButton cartb;
    private javax.swing.JButton homeb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel logo;
    private javax.swing.JButton nikeb;
    private javax.swing.JButton pumab;
    private javax.swing.JLabel pumasmash;
    private javax.swing.JLabel pumatrainer;
    private javax.swing.JTextField searchbar;
    private javax.swing.JLabel speedcat;
    // End of variables declaration//GEN-END:variables
}
